#!/usr/bin/env bash

rm -rf client service

mkdir client && cd client
echo "client-only file" > client-only.txt
echo "shared file" > shared-file.txt

mkdir shared-dir
echo "shared file" > shared-dir/shared-file.txt
cd ..

mkdir service && cd service
echo "service-only file" > service-only.txt
echo "shared file" > shared-file.txt

mkdir service-only-dir shared-dir
echo "service-only file" > service-only-dir/service-only.txt
echo "service-only file" > shared-dir/service-only.txt
echo "shared file" > shared-dir/shared-file.txt